import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#191919',
  },
  workshopContainer: {
    width: width * 0.9,
    height: height * 0.09,
    backgroundColor: '#666666',
    alignSelf: 'center',
    borderRadius: 16,
    justifyContent: 'center',
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  profileContainer: {
    width: 50,
    height: 50,
    borderRadius: 50,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileImage: {
    width: 30,
    height: 30,
  },
  shopnameContainer: {
    marginLeft: 10,
  },
  shopnameText: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '600',
    lineHeight: 30,
  },
  chatContainer: {
    flex: 1,
    marginTop: 24,
    backgroundColor: '#303030',
    padding: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  chatBox: {
    width: width * 0.8,
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#ffffff',
    marginBottom: 10,
  },
  senderMessage: {
    alignSelf: 'flex-end',
    backgroundColor: '#ffffff',
    padding: 10,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 2,
    marginBottom: 10,
    maxWidth: '80%',
  },
  receiverMessage: {
    alignSelf: 'flex-start',
    backgroundColor: '#666666',
    padding: 10,
    marginBottom: 10,
    maxWidth: '80%',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 2,
    borderBottomRightRadius: 20,
  },
  messageSenderText: {
    fontSize: 12,
    fontWeight: '400',
  },
  messageReceiverText: {
    fontSize: 12,
    fontWeight: '400',
    color: '#ffffff',
  },
  sendContainer: {
    color: '#ffffff',
    width: width,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 10,
    backgroundColor: '#ffffff',
  },
  input: {
    width: width * 0.8,
    height: 40,
    backgroundColor: '#dedede',
    borderRadius: 20,
    padding: 10,
  },
  sendImage: {
    width: width * 0.1,
    height: width * 0.1,
  },
  exitButton: {
    position: 'absolute',
    top: height * 0.12,
    right: width * 0.05,
    backgroundColor: '#ffffff',
    padding: 10,
    borderRadius: 5,
    borderColor: '#C7C7C7',
    borderWidth: 1,
    zIndex: 1,
  },
  exitButtonText: {
    color: '#FF6565',
    fontSize: 14,
  },
  requestContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 10,
    paddingLeft: 10,
    backgroundColor: '#ffffff',
    gap: width * 0.03,
  },
  requestButton: {
    backgroundColor: '#dedede',
    padding: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    gap: width * 0.02,
  },
  requestButtonText: {
    color: '#585858',
    fontSize: 10,
    fontWeight: '600',
    alignSelf: 'center',
  },
  requestImage: {
    width: 14,
    height: 14,
    resizeMode: 'contain',
  },
});
export default styles;